apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: chuongltv/db-k8s:v1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123123"
        - name: MYSQL_DATABASE
          value: "tintuc_db"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "123123"
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
